version: '2'

services:
  consul:
    image: "consul"
    networks:
      main:
        aliases:
          - consul
    ports:
      - "8500:8500"
    restart: always

  hivemq_node1:
    image: hivemq-consul-cluster-discovery
    networks:
      main:
        aliases:
          - hivemq_node1
    ports:
      - "1883:1883"
    environment:
      - CONSUL_TOKEN=test_token

  hivemq_node2:
    image: hivemq-consul-cluster-discovery
    networks:
      main:
        aliases:
          - hivemq_node2
    ports:
     - "2883:1883"
    environment:
      - CONSUL_TOKEN=test_token

networks:
  main: